name: ESLint linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies
        run: |
          npm i -g eslint-plugin-no-unsanitized@latest eslint@latest
          echo "`npm config get prefix`/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v3

      - name: Run linter
        run: make -k FORMAT=stylish
