name: ESLint linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies
        run: npm i eslint-plugin-no-unsanitized@latest eslint@latest

      - name: Run linter
        run: make -k FORMAT=stylish
